spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Pokémon Trade Card Collection
  datasource:
    url: jdbc:h2:mem:projeto-sete-vidas-gerenciamento
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
server:
  servlet:
    context-path: /projeto-sete-vidas/v1
  port: '8080'
